name: DirectNet.Net-Publish

on:
  push:
    branches:
      - main
    paths-include:
      - DirectNet.Net/**
    paths-ignore:
      - .github/workflows/**
  workflow_dispatch:

env:
  name: PROJECT_PATH
  value: DirectNet.Net/DirectNet.Net.csproj

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet build $PROJECT_PATH -c Release -o bin/Release

      - name: Push the package to nuget.org
        run: |
          # Extract the version from the csproj file
          $VERSION=@(([xml] (Get-Content .\DirectNet.Net\DirectNet.Net.csproj -Encoding utf8)).Project.PropertyGroup.Version)[1]

          # Publish the package to nuget.org
          dotnet nuget push ./bin/Release/DirectNet.Net.$VERSION.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.DirectNetAPIKey }}
