name: ErabliereAPI.Proxy-Publish

on:
  push:
    branches:
      - master
    paths-include:
      - DirectNet.Net/**
      - .github/workflows/directnet-nuget-publish.yaml
  workflow_dispatch:

env:
  name: PROJECT_PATH
  value: DirectNet.Net/DirectNet.Net.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet build $PROJECT_PATH -c Release -o bin/Release

      - name: Push the package to nuget.org
        run: |
          # Extract the version from the csproj file
          VERSION=$(grep -Eoi "<version>([[:digit:]\.]+)</version>" DirectNet.Net/DirectNet.Net.csproj | sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p')

          # Publish the package to nuget.org
          dotnet nuget push ./bin/Release/DirectNet.Net.$VERSION.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.DirectNetAPIKey }}
