name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/directnet-nuget-publish.yaml
  pull_request:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/directnet-nuget-publish.yaml

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
